baseURL = "https://oledz.github.com/risma"
languageCode = "en-us"
title = "Risma"
theme = "risma"

# Menus
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 20
[[menu.main]]
    name = "Pricing"
    url = "/pricing"
    weight = 30
[[menu.main]]
    name = "Contact"
    url = "/contacts"
    weight = 40

# Usernames for Email, Social Media and Online Accounts
[params.Social]
    email = "info@risma.com"
    facebook = "risma"
    twitter = "risma"
	instagram = "risma"
	tumblr = "risma"
	reddit = "risma"
	pinterest = "risma"
	youtube = "risma"
    vimeo = "risma"
	weibo = "risma"
	vk = "risma"
	linkedin = "risma"

	# Writing
    medium = ""
	blogger = ""
	wordpress = ""

	# Creative & Visual
    dribbble = ""
	behance = ""
	deviantart = ""
	flickr = ""

    # Audio & Music
    soundcloud = ""

	# Programming
    github = ""
	stackoverflow = ""
	gitlab = ""
	codepen = ""

    # Academic
    googlescholar = ""
    impactstory = ""
    orcid = ""  
